# -*- coding: utf-8 -*-
"""Number Guessing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zR5zP9MU2hUdSQMJkXAQluG-_r657bYi
"""

import random

list= range(30) 
#range of values to guess from

#function to give hints based on how close the input value is to the target value
def hint():
  if(abs(inp-e)<=2):
    print('So close!')
  elif(abs(inp-e)>=len(list)/2):
    print("You're way off!")
  elif(e<inp):
    print('Try a lower value')
  else:
    print('Try a higher value')

print("Let's play a guessing game!\n\nGuess a number correctly between 0 and 30. Maximum score is 50\n")
a=random.randint(0,30)
e=list[a]
#print(e) 
#in case we wish to see the target value
sc=50
inp=-1
#Initializing score as 50 and input as -1
while(inp!=e):
  inp=int(input('Guess a number '))
  if(inp==e):
    print("Your guess is correct! \nScore : "+str(sc))
  else:
    h=input('Your guess is incorrect. Would you like a hint? (y/n) Note : Score will be reduced by 2 points')
    if(h=='y' or h=='Y'):
      sc-=2
      #Score decreases by 2 for every hint
      hint()